# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170630_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenerurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
